apiVersion: v1
kind: Service
metadata:
  name: my-app-node-port
  namespace: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30004
