apiVersion: v1
kind: Service
metadata:
  name: my-app-load-balancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: aws.leepowell.co.uk
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8888
