apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-label
  template:
    metadata:
      name: my-app
      labels:
        app: my-app-label
    spec:
      containers:
      - name: my-app
        image: leepowell/my-app
        imagePullPolicy: Never
